[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  SECRETS_SCAN_OMIT_PATHS = ".netlify/.next/cache"

[[plugins]]
  package = "@netlify/plugin-nextjs"
